### ISSUE TITLE
Not being able to build the game  

### ISSUE THREAD

**Issue by py4object** [DanEEStar/antworld#1]
gulp 

[01:36:31] Using gulpfile /srv/http/antworld/gulpfile.js
[01:36:31] Starting 'clean'...
[01:36:31] Finished 'clean' after 58 ms
[01:36:31] Starting 'default'...
[01:36:31] Starting 'styles'...
[01:36:31] Starting 'scripts'...
[01:36:31] Starting 'copyPixelFont'...
[01:36:31] Finished 'copyPixelFont' after 2.29 ms
[01:36:31] Finished 'default' after 372 ms
[01:36:31] gulp-size: total 0 B
[01:36:31] Finished 'scripts' after 251 ms
[01:36:31] gulp-size: total 196 B
[01:36:31] Finished 'styles' after 658 ms
[01:36:31] Starting 'html'...
[01:36:32] 'html' errored after 131 ms
[01:36:32] TypeError: $.useref.assets is not a function
    at Gulp.<anonymous> (/srv/http/antworld/gulpfile.js:42:24)
    at module.exports (/srv/http/antworld/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/srv/http/antworld/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/srv/http/antworld/node_modules/orchestrator/index.js:214:10)
    at /srv/http/antworld/node_modules/orchestrator/index.js:279:18
    at finish (/srv/http/antworld/node_modules/orchestrator/lib/runTask.js:21:8)
    at /srv/http/antworld/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/srv/http/antworld/node_modules/once/once.js:17:25)
    at Transform.onend (/srv/http/antworld/node_modules/end-of-stream/

**Comment by DanEEStar** [comment]
I removed the dependency to gulp and bower.
The compile step is now done directly with `npm run coffee`.
The following steps are now needed to compile and run the game locally

```
npm install
npm start
```

I hope this helps!
